
[AtCoder]
  ContestID = "abc169"
  ContestURL = "https://atcoder.jp/contests/abc169"
  TaskID = "abc169_d"
  TaskName = "D - Div Game"
  TaskURL = "https://atcoder.jp/contests/abc169/tasks/abc169_d"

[Environment]
  BuildCmd = ""
  BuildCmdOnDocker = ""
  CleanCmd = ""
  Cmd = "python3 -B main.py"
  CmdOnDocker = "python3 -B main.py"
  DockerImage = "docker.io/library/python:3.4.3-slim"
  Key = "python3"
  Language = "Python3 (3.4.3)"
  LanguageCode = "4006"
  Note = ""
  SrcName = "main.py"
  Template = "internal/python3/main.py"
