
[AtCoder]
  ContestID = "abc163"
  ContestURL = "https://atcoder.jp/contests/abc163"
  TaskID = "abc163_d"
  TaskName = "D - Sum of Large Numbers"
  TaskURL = "https://atcoder.jp/contests/abc163/tasks/abc163_d"

[Environment]
  BuildCmd = ""
  BuildCmdOnDocker = ""
  CleanCmd = ""
  Cmd = "python3 -B main.py"
  CmdOnDocker = "python3 -B main.py"
  DockerImage = "docker.io/library/python:3.4.3-slim"
  Key = "python3"
  Language = "Python3 (3.8.2)"
  LanguageCode = "4006"
  Note = ""
  SrcName = "main.py"
  Template = "internal/python3/main.py"
